In [1]:
import numpy as np

In [5]:
vector = np.arange(1, 11)
print(vector)


[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
mat= np.zeros((3,3))
print(mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
matrix = np.random.randint(1, 11, (5, 5))
print(matrix)

[[10  4  7  5  5]
 [ 8  3  3  5  2]
 [10  8  8  2  9]
 [ 9 10 10  3  6]
 [ 3  2 10  6  8]]


In [9]:
matrix = np.random.rand(4, 4)
print(matrix)

[[0.53973609 0.43954383 0.9141197  0.23617375]
 [0.95986144 0.54539536 0.120914   0.49833219]
 [0.79182185 0.98988308 0.65581311 0.52714911]
 [0.70621736 0.11259255 0.33254872 0.54362805]]


In [11]:
a = np.random.randint(1, 11, 5)
b = np.random.randint(1, 11, 5)
print(a)
print(b)
print("Додавання:", a + b)
print("Віднімання:", a - b)
print("Множення:", a * b)

[3 8 6 6 9]
[ 3  8 10  1  7]
Додавання: [ 6 16 16  7 16]
Віднімання: [ 0  0 -4  5  2]
Множення: [ 9 64 60  6 63]


In [13]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([7, 6, 5, 4, 3, 2, 1])
dot_product = np.dot(a, b)
print("Скалярний добуток:", dot_product)

Скалярний добуток: 84


In [14]:
A = np.random.randint(1, 11, (2, 2))
B = np.random.randint(1, 11, (2, 3))
C = np.dot(A, B)
print(A)
print(B)
print(C)

[[1 6]
 [5 3]]
[[8 1 4]
 [3 4 8]]
[[26 25 52]
 [49 17 44]]


In [17]:
A = np.random.randint(1, 11, (3, 3))
A_inv = np.linalg.inv(A)

print(A)
print(A_inv)

[[5 6 4]
 [3 1 3]
 [5 1 6]]
[[-0.27272727  2.90909091 -1.27272727]
 [ 0.27272727 -0.90909091  0.27272727]
 [ 0.18181818 -2.27272727  1.18181818]]


In [18]:
A = np.random.rand(4, 4)

print(A)
print( A.T)

[[0.65768532 0.09272382 0.12710272 0.97274642]
 [0.84991028 0.83218524 0.11562631 0.43712031]
 [0.13707785 0.52532314 0.33718667 0.68409134]
 [0.7308778  0.11321642 0.109328   0.09158418]]
[[0.65768532 0.84991028 0.13707785 0.7308778 ]
 [0.09272382 0.83218524 0.52532314 0.11321642]
 [0.12710272 0.11562631 0.33718667 0.109328  ]
 [0.97274642 0.43712031 0.68409134 0.09158418]]


In [19]:
A = np.random.randint(1, 11, (3, 4))
v = np.random.randint(1, 11, 4)

result = np.dot(A, v)

print(A)
print(v)
print(result)

[[10  7  3  3]
 [ 6  2  4  5]
 [ 2  5  1  3]]
[10  1  1 10]
[140 116  56]


In [22]:
A = np.random.rand(2, 3)
v = np.random.rand(3)

result = np.dot(A, v)

print(A)
print(v)
print(result)

[[0.13539381 0.41027792 0.53624556]
 [0.22295416 0.02074607 0.44988202]]
[0.79022113 0.17820176 0.63975898]
[0.52317121 0.46769614]


In [21]:
A = np.random.randint(1, 11, (2, 2))
B = np.random.randint(1, 11, (2, 2))


print(A)
print(B)
print(A*B)


[[3 3]
 [4 8]]
[[4 4]
 [6 2]]
[[12 12]
 [24 16]]


In [24]:
A = np.random.randint(1, 11, (2, 2))
B = np.random.randint(1, 11, (2, 2))

print(A)
print(B)
print(np.dot(A, B))

[[9 5]
 [6 8]]
[[4 1]
 [6 3]]
[[66 24]
 [72 30]]


In [25]:
A = np.random.randint(1, 101, (5, 5))

print(A)
print(np.sum(A))

[[ 9 11 64 65 85]
 [51 15 49 90 38]
 [28 78  1 13 55]
 [58 74 24 19 50]
 [73 31 45 61 24]]
1111


In [35]:
A = np.random.randint(1, 11, (4, 4))
B = np.random.randint(1, 11, (4, 4))

print(A)
print(B)
print(A - B)

[[ 6  4  5  6]
 [ 4  1  5  4]
 [ 5  2  4 10]
 [ 1  6  1  7]]
[[ 6  5  8  6]
 [ 1 10  9  7]
 [ 5  5  9  6]
 [ 7  2  2  1]]
[[ 0 -1 -3  0]
 [ 3 -9 -4 -3]
 [ 0 -3 -5  4]
 [-6  4 -1  6]]


In [36]:
A = np.random.rand(3, 3)

row_sums = np.sum(A, axis=1).reshape(-1, 1)

print(row_sums)

[[1.43969867]
 [0.81914928]
 [1.78511308]]


In [37]:
A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

B = A ** 2

print(A)
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [39]:
v = np.random.randint(1, 51, 4)

roots = np.sqrt(v)

print(v)
print(roots)

[24 11 47 23]
[4.89897949 3.31662479 6.8556546  4.79583152]
